### ISSUE TITLE
[Host.Kafka] Upgrade docker test container to latest Kafka cluster image

### ISSUE THREAD

**Issue by zarusz** [zarusz/SlimMessageBus#305]
The docker-compose file uses an old Kafka version for our integration tests.
We need to use latest and preferably use the confluent community distro [confluentinc/cp-kafka:7.3.10](https://hub.docker.com/layers/confluentinc/cp-kafka/7.3.10/images/sha256-812a9df1d01cb0eadf7035a38d1d5a0e56f15c8aa3dd8e52c0bcd619609c53d2?context=explore).

Right now is uses the [wurstmeister/kafka:2.13-2.8.1](https://hub.docker.com/layers/wurstmeister/kafka/2.13-2.8.1/images/sha256-1e05be28055c8c3527ba4f892b5574411ee713899d1181d43dfdbc4dffcf78df?context=explore)

```yml
  zookeeper:
    container_name: slim.zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - slim

  kafka:
    container_name: slim.kafka
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "user-test-ping:2:1,user-test-echo:2:1,user-test-echo-resp:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - slim
```
